// UI strings in one place (English only for now; ready for i18n later).
export const strings = {
  skipToContent: "Skip to content",
  nav: {
    main: "Main",
    home: "Home",
    activities: "Activities",
    categories: "Categories",
    scrollCategoriesLeft: "Show previous categories",
    scrollCategoriesRight: "Show more categories",
    mobile: "Mobile",
    search: "Search",
    favorites: "Favorites",
    account: "Account",
    settings: "Settings",
    footer: "Footer",
  },
  account: {
    logIn: "Log in",
    signUp: "Sign up",
    menu: "Account menu",
    dashboard: "Dashboard",
    logOut: "Log out",
  },
  theme: {
    label: "Theme",
    system: "System",
    dark: "Dark",
    light: "Light",
    sepia: "Sepia",
  },
  settings: {
    title: "Settings",
    close: "Close",
  },
  footer: {
    about: "About",
    faq: "FAQ",
    contact: "Contact",
    privacy: "Privacy",
    terms: "Terms",
    tagline: "Interactive English activities for ESL teachers.",
  },
  notFound: {
    title: "Page not found",
    description: "The page you're looking for doesn't exist or was moved.",
    cta: "Browse activities",
  },
  comingSoon: "Coming soon",
  catalog: {
    title: "Fun English Activities",
    count: (n: number) =>
      `${n.toLocaleString("en-US")} Interactive ${n === 1 ? "Activity" : "Activities"} for ESL Teachers`,
    searchLabel: "Search activities",
    searchPlaceholder: "Search by topic, level, grammar point, or activity name…",
    whatsNew: "What's New",
    whatsNewSubtitle: "Recently added activities",
    seeAll: "See All",
    carouselLabel: (section: string) => `${section} activities`,
    seeAllIn: (section: string) => `See all ${section} activities`,
    previous: (section: string) => `Previous ${section} activities`,
    next: (section: string) => `Next ${section} activities`,
    newBadge: "New",
    loginToFavorite: "Log in to save favorites",
    share: "Share",
    linkCopied: "Link copied",
    empty: "No activities yet. Check back soon!",
    showing: (n: number) =>
      `Showing ${n.toLocaleString("en-US")} ${n === 1 ? "activity" : "activities"}`,
    categoryFilter: "Category",
    allCategories: "All Categories",
    levelFilter: "Level",
    allLevels: "All Levels",
    sortLabel: "Sort by",
    sorts: { newest: "Newest First", "title-asc": "Title: A-Z", "title-desc": "Title: Z-A" },
    levels: { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" },
    clearFilters: "Clear filters",
    results: "Search results",
    noResults: "No activities found",
    noResultsHint: "Try other words or clear the filters.",
    loadMore: "Load more",
    loading: "Loading activities",
  },
} as const;
