// UI strings in one place (English only for now; ready for i18n later).
export const strings = {
  skipToContent: "Skip to content",
  nav: {
    main: "Main",
    home: "Home",
    activities: "Activities",
    categories: "Categories",
    scrollCategoriesLeft: "Show previous categories",
    scrollCategoriesRight: "Show more categories",
    mobile: "Mobile",
    search: "Search",
    favorites: "Favorites",
    account: "Account",
    settings: "Settings",
    footer: "Footer",
  },
  account: {
    logIn: "Log in",
    signUp: "Sign up",
    menu: "Account menu",
    dashboard: "Dashboard",
    logOut: "Log out",
  },
  theme: {
    label: "Theme",
    system: "System",
    dark: "Dark",
    light: "Light",
    sepia: "Sepia",
  },
  settings: {
    title: "Settings",
    close: "Close",
  },
  footer: {
    about: "About",
    faq: "FAQ",
    contact: "Contact",
    privacy: "Privacy",
    terms: "Terms",
    tagline: "Interactive English activities for ESL teachers.",
  },
  notFound: {
    title: "Page not found",
    description: "The page you're looking for doesn't exist or was moved.",
    cta: "Browse activities",
  },
  auth: {
    loginTitle: "Log in",
    loginSubtitle: "Welcome back! Log in to see your favorites.",
    signupTitle: "Create your free account",
    signupSubtitle: "Save favorites and build lists for your classes.",
    resetTitle: "Reset your password",
    resetSubtitle: "We'll email you a link to choose a new password.",
    name: "Name",
    email: "Email",
    password: "Password",
    passwordHint: "At least 8 characters",
    logIn: "Log in",
    signUp: "Create account",
    sendLink: "Send reset link",
    google: "Continue with Google",
    or: "or",
    forgot: "Forgot password?",
    noAccount: "New here?",
    createOne: "Create an account",
    haveAccount: "Already have an account?",
    logInInstead: "Log in",
    backToLogin: "Back to log in",
    resetSent: "If an account exists for that email, we sent you a reset link.",
    working: "Please wait…",
    errors: {
      emailInUse: "This email is already registered. Log in instead?",
      wrongCredentials: "Wrong email or password.",
      weakPassword: "Use at least 8 characters.",
      invalidEmail: "Please enter a valid email.",
      nameRequired: "Please enter your name.",
      tooManyRequests: "Too many attempts. Please try again in a few minutes.",
      network: "Can't connect. Check your internet and try again.",
      popupBlocked: "Your browser blocked the Google window. Allow pop-ups and try again.",
      generic: "Something went wrong. Please try again.",
    },
  },
  player: {
    editActivity: "Edit activity",
    start: "Start",
    options: "Options",
    shuffle: "Shuffle questions",
    teams: "Teams",
    noTeams: "No teams",
    teamCount: (n: number) => `${n} teams`,
    team: (n: number) => `Team ${n}`,
    teamName: (n: number) => `Name of team ${n}`,
    timer: "Timer",
    noTimer: "No timer",
    seconds: (n: number) => `${n} seconds`,
    progress: (current: number, total: number) => `${current} / ${total}`,
    progressLabel: "Progress",
    score: "Score",
    points: (n: number) => `${n} ${n === 1 ? "point" : "points"}`,
    restart: "Restart",
    fullscreen: "Fullscreen",
    exitFullscreen: "Exit fullscreen",
    exit: "Exit",
    results: "Results",
    correctOf: (correct: number, total: number) => `${correct} / ${total} correct`,
    time: (seconds: number) =>
      `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`,
    timeLabel: "Time",
    review: "Review",
    correctAnswer: "Correct answer",
    yourAnswer: "Your answer",
    winner: (name: string) => `${name} wins!`,
    tie: "It's a tie!",
    playAgain: "Play again",
    backToActivities: "Back to activities",
    loadError: "This activity couldn't be loaded",
    loadErrorHint: "Something is wrong with its content. Please try another activity.",
    unsupported: "This type of activity is coming soon",
    unsupportedHint: "It can't be played yet. Try one of the quizzes in the meantime!",
    notFound: "Activity not found",
    notFoundHint: "It may have been removed or isn't published yet.",
    loading: "Loading activity",
    madeWith: "Made with Fun English",
    listen: "Listen",
    clipUnavailable: "This clip can't be played here",
    watchOnYouTube: "Watch on YouTube",
    replayClip: "Replay clip",
  },
  flashcards: {
    flip: "Flip",
    showBack: "Card front. Select to see the word",
    showFront: "Card back. Select to see the front",
    previous: "Previous card",
    next: "Next card",
    knewIt: "I knew it",
    stillLearning: "Still learning",
    review: (n: number) => `Review the ${n} ${n === 1 ? "card" : "cards"} you're still learning`,
    knewOf: (knew: number, total: number) => `You knew ${knew} of ${total} cards`,
    reviewed: (n: number) => `${n} ${n === 1 ? "card" : "cards"} reviewed`,
    startWith: "Start with",
    picture: "Picture",
    word: "Word",
    selfCheck: "Self-check (I knew it / Still learning)",
  },
  blanks: {
    gap: (n: number, word?: string) => (word ? `Gap ${n}: ${word}` : `Gap ${n}`),
    bank: "Word bank",
    right: "Correct",
    wrong: "Incorrect",
    showAnswer: "Show answer",
    showHint: "Show hint",
    score: (correct: number, total: number) => `${correct} of ${total} correct`,
  },
  sentenceOrder: {
    prompt: "Put the words in order",
    answerLine: "Your sentence",
    tray: "Pieces",
    empty: "Tap the pieces below to build the sentence.",
    add: (piece: string) => `Add “${piece}”`,
    remove: (piece: string, position: number) =>
      `Remove “${piece}” (position ${position}) from your sentence`,
    wrongPlace: "in the wrong place",
    keyboardHint: "Enter adds a piece · Backspace removes the last one",
    correct: "Correct!",
    wrong: "Not quite. The highlighted pieces are in the wrong place.",
    tryAgain: "Try again",
    showAnswer: "Show answer",
    readAloud: "Read aloud",
    showTranslation: "Show translation",
    readAloudOption: "Read the sentence aloud when it's right",
  },
  board: {
    board: "Game board",
    cell: (category: string, value: number, used: boolean) =>
      `${category} – ${value}${used ? " (already played)" : ""}`,
    showAnswer: "Show answer",
    whoGotIt: "Who got it right?",
    noOne: "No one",
    penalize: (team: string, value: number) => `${team} −${value}`,
    backToBoard: "Back to the board",
    adjust: "Adjust scores:",
    adjustBy: (team: string, delta: number) => `${team} ${delta > 0 ? "+" : "−"}${Math.abs(delta)}`,
    endGame: "End game",
    played: (used: number, total: number) => `${used} of ${total} clues played`,
    penaltyOption: "Wrong answers lose points",
  },
  cards: {
    or: "or",
    followUps: "Show follow-up questions",
    vocabulary: "Show useful vocabulary",
    startTimer: "Start timer",
    pauseTimer: "Pause",
    resetTimer: "Reset timer",
    random: "Random card",
    allShown: "All cards shown – Start over?",
    startOver: "Start over",
    finish: "Finish",
    writeHere: "Write your answer here…",
    words: (n: number) => `${n} ${n === 1 ? "word" : "words"}`,
    discussed: (n: number) => `${n} ${n === 1 ? "card" : "cards"} discussed`,
    written: (n: number) => `${n} ${n === 1 ? "prompt" : "prompts"} done`,
    speakingTimer: "Speaking timer",
    off: "Off",
    sound: "Sound at the end",
  },
  favorites: {
    add: (title: string) => `Add to favorites: ${title}`,
    remove: (title: string) => `Remove from favorites: ${title}`,
    saved: "Saved to favorites",
    removed: "Removed from favorites",
    addToList: "Add to list",
    saveError: "Couldn't save. Try again.",
    favoritesLimit: (n: number) => `You've reached the limit of ${n} favorites`,
    listsLimit: (n: number) => `You've reached the limit of ${n} lists`,
    loginTitle: "Log in to save favorites",
    loginText:
      "Create a free account to save activities and organize them in lists for your classes.",
    listsTitle: "Add to a list",
    listsEmpty: "No lists yet. Create one for a class or a topic.",
    newList: "New list",
    newListPlaceholder: "e.g. Monday – Teens B1",
    create: "Create",
    done: "Done",
  },
  dashboard: {
    welcome: (name: string) => `Welcome back, ${name}`,
    welcomeAnonymous: "Welcome back",
    subtitle: "Your favorites, class lists and recent activities.",
    favorites: "Favorites",
    favoritesCount: (n: number) => `${n} saved`,
    lists: "My lists",
    classes: "My classes",
    tracks: "Learning tracks",
    recent: "Recently played",
    browse: "Browse activities",
    emptyFavorites: "Tap the heart on any activity to save it here.",
    emptyLists: 'Save a favorite and choose "Add to list" to group activities by class or topic.',
    emptyRecent: "Activities you start will show up here.",
    unavailable: "This activity is no longer available",
    remove: "Remove",
    open: (name: string) => `Open ${name}`,
    close: "Close list",
    rename: "Rename",
    renameList: (name: string) => `Rename ${name}`,
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    deleteList: (name: string) => `Delete ${name}`,
    confirmDelete: (name: string) =>
      `Delete the list "${name}"? Its activities stay in your favorites.`,
    listCount: (n: number) => `${n} ${n === 1 ? "activity" : "activities"}`,
    emptyList: 'This list is empty. Use "Add to list" after saving a favorite.',
    sectionsNav: "Dashboard sections",
  },
  tracks: {
    title: "Learning Tracks",
    subtitle: "Organized sequences of activities with progress tracking per student.",
    newTrack: "New track",
    createFromList: "Create from list",
    createFromListTitle: "Create Track from List",
    selectListPrompt: "Choose one of your favorite lists to copy as an ordered learning track:",
    noListsAvailable: "No lists available to copy from. Save activities to a list first.",
    emptyTracks: "No learning tracks created yet. Create a track to map out learning journeys for your students.",
    activitiesCount: (n: number) => `${n} ${n === 1 ? "activity" : "activities"}`,
    assignedCount: (c: number, s: number) => {
      const parts = [];
      if (c > 0) parts.push(`${c} ${c === 1 ? "class" : "classes"}`);
      if (s > 0) parts.push(`${s} ${s === 1 ? "student" : "students"}`);
      return parts.length > 0 ? `Assigned to ${parts.join(", ")}` : "Not assigned yet";
    },
    countClassActivities: "Count class activities",
    countClassActivitiesHint: "Automatically mark steps when played during classroom sessions",
    editTrack: "Edit track",
    assignTrack: "Assign",
    classMatrix: "Class matrix",
    deleteTrack: "Delete track",
    confirmDelete: (name: string) =>
      `Delete learning track "${name}"? Assigned students' progress records will also be removed.`,
    editorTitleNew: "Create Learning Track",
    editorTitleEdit: "Edit Learning Track",
    nameLabel: "Track Name",
    namePlaceholder: "e.g. Travel Module or Starter Level A1",
    descriptionLabel: "Description (optional)",
    descriptionPlaceholder: "What will students achieve in this track?",
    levelLabel: "Level (optional)",
    allLevels: "All levels",
    activitiesLabel: "Activities (1 to 30)",
    addActivity: "Add activity",
    searchActivityPlaceholder: "Search activities to add…",
    moveUp: "Move up",
    moveDown: "Move down",
    removeStep: "Remove step",
    minActivitiesError: "A track must contain at least 1 activity.",
    maxActivitiesError: "A track cannot contain more than 30 activities.",
    nameRequiredError: "Please enter a track name (1-60 characters).",
    assignTitle: (name: string) => `Assign "${name}"`,
    assignClassesHeading: "Assign to classes",
    assignStudentsHeading: "Assign to individual students",
    noClasses: "No classes available.",
    noStudents: "No students available.",
    saveAssignment: "Save assignment",
    assignSuccess: "Track successfully assigned!",
    progressPercent: (pct: number) => `${pct}% complete`,
    stepsCompleted: (done: number, total: number) => `${done} of ${total} steps completed`,
    statusCompleted: "Completed",
    statusCurrent: "Current step",
    statusPending: "Pending",
    statusUnavailable: "No longer available",
    markCompleted: "Mark completed",
    markPending: "Mark uncompleted",
    sourceManual: "Manual",
    sourceHomework: "Homework",
    sourceClass: "Class",
    unassign: "Unassign track",
    confirmUnassign: (name: string) => `Unassign track "${name}" from this student?`,
    matrixTitle: (name: string) => `Class Matrix: ${name}`,
    studentColumn: "Student",
    progressColumn: "Progress",
    stepColumn: (n: number) => `Step ${n}`,
    noStudentsInClass: "No students in this class.",
    legendCompleted: "Completed",
    legendCurrent: "Next up",
    legendPending: "Pending",
    legendUnavailable: "Unavailable",
    portalTab: "Learning Track",
    playCurrentStep: "Play current activity",
    playActivity: "Play activity",
    congratulationsAllCompleted: "Congratulations! You've completed all activities in this track! 🎉",
  },
  classes: {
    title: "My classes",
    classesCount: (n: number) => `${n} ${n === 1 ? "class" : "classes"}`,
    activeTab: "Active",
    archivedTab: "Archived",
    newClass: "New class",
    createClass: "Create class",
    classNamePlaceholder: "Class name (e.g. Teens B1)",
    emptyActive:
      "You don't have any active classes yet. Create one above to organize your students.",
    emptyArchived: "No archived classes.",
    archive: "Archive",
    restore: "Restore",
    confirmArchive: (name: string) => `Archive class "${name}"? It will move to the Archived tab.`,
    confirmDeleteClass: (name: string) =>
      `Delete class "${name}"? Students will remain registered, but this class will be deleted.`,
    studentCount: (n: number) => `${n} ${n === 1 ? "student" : "students"}`,
    addStudent: "Add student",
    batchAddPrompt: "Paste student names, one per line (up to 40 at a time):",
    batchAddPlaceholder: "Ana Silva\nLucas Costa\nMarina Rocha",
    batchAddButton: "Paste name list",
    batchAddConfirm: "Add names",
    singleAddButton: "Single student",
    studentNamePlaceholder: "Full name (e.g. Ana Silva)",
    studentEmailPlaceholder: "Email address (optional)",
    editStudent: "Edit student",
    saveStudent: "Save",
    copyToClass: "Copy to class",
    moveToClass: "Move to class",
    removeFromClass: "Remove from class",
    deleteStudent: "Delete student",
    deleteStudentWarning: (name: string) =>
      `Delete student "${name}"? This action cannot be undone. All associated grades, progress tracks, homework submissions, and vocabulary will be permanently deleted.`,
    pinTitle: "Homework PIN",
    pinGenerated: (pin: string) =>
      `PIN generated: ${pin}. Share this 4-digit code with the student for homework access.`,
    pinLabel: "Homework PIN:",
    regeneratePin: "Regenerate PIN",
    confirmRegeneratePin:
      "Generate a new homework PIN for this student? The previous PIN will stop working immediately.",
    selectTargetClass: "Select class...",
    viewStudent: "View student profile",
    noStudents: "No students in this class yet. Add students one by one or paste a list of names.",
    printPins: "Print PINs",
    printPinsTitle: "Class Homework PINs",
    printPinsDesc: "Print or share these 4-digit PINs with your students so they can access homework links.",
    printButton: "Print PIN cards",
    closeModal: "Close",
    cancel: "Cancel",
  },
  student: {
    backToClasses: "Back to classes",
    notFound: "Student not found",
    notFoundDesc: "The student record may have been deleted or belongs to another teacher account.",
    classesHeading: "Enrolled Classes",
    noClasses: "Not currently enrolled in any class.",
    homeworkPinHeading: "Homework PIN",
    homeworkPinDesc:
      "Students use this 4-digit code to access assigned homework without needing an email account.",
    regeneratePinButton: "Generate new PIN",
    gradesSectionTitle: "Grades & Errors",
    gradesSectionEmpty:
      "No recorded grades or errors yet. Classroom sessions and evaluations will appear here.",
    progressSectionTitle: "Progress Tracks",
    progressSectionEmpty: "No progress track assigned yet. Milestones and paths will appear here.",
    homeworkSectionTitle: "Homework",
    homeworkSectionEmpty: "No homework submissions recorded yet.",
    vocabularySectionTitle: "Vocabulary Bank",
    vocabularySectionEmpty: "No vocabulary saved for this student yet.",
  },
  notes: {
    title: "Grades & Errors",
    subtitle: "Track pronunciation, grammar, vocabulary and student strengths across sessions.",
    quickCaptureTitle: "Quick Note Capture",
    quickCaptureDesc:
      "Type a note and press Enter to save. Student selection stays active for rapid logging.",
    categories: {
      pronunciation: "Pronunciation",
      grammar: "Grammar",
      vocabulary: "Vocabulary",
      fluency: "Fluency",
      strength: "Strength",
      general: "General",
    },
    visibilities: {
      private: "Private (teacher only)",
      shared: "Shared (student portal)",
    },
    statuses: {
      open: "Open",
      resolved: "Resolved",
      all: "All",
    },
    filterCategory: "Category",
    filterVisibility: "Visibility",
    filterStatus: "Status",
    allCategories: "All categories",
    allVisibilities: "All visibilities",
    placeholderText:
      "Note content (e.g. said 'thought' with /f/ sound or said 'he go' → should be 'he goes')...",
    placeholderCorrection: "Correction (optional, e.g. said X → should be Y)",
    addNote: "Add note",
    saveNote: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    confirmDelete: "Delete this note permanently?",
    resolve: "Mark as resolved",
    unresolve: "Reopen",
    resolvedBadge: "Resolved",
    privateBadge: "Private",
    sharedBadge: "Shared",
    recurringTitle: "Recurring Issues",
    recurringDesc: "Issues recorded across 2 or more different classes.",
    classesCount: (n: number) => `${n} ${n === 1 ? "class" : "classes"}`,
    wholeGroup: "Whole group",
    selectStudents: "Select students",
    selectedStudentsCount: (n: number) => `${n} ${n === 1 ? "student" : "students"} selected`,
    projectionMode: "Projection mode",
    projectionModeNotice: "Projection mode is active. Notes list is hidden from class view.",
    emptyNotes: "No notes recorded yet for this student.",
    emptyFiltered: "No notes match the selected filters.",
    validationEmpty: "Note text cannot be empty.",
    validationTooLong: "Note text cannot exceed 500 characters.",
    validationCorrectionTooLong: "Correction cannot exceed 500 characters.",
    noteSaved: "Note saved successfully.",
    notesBatchSaved: (n: number) => `Note saved for ${n} ${n === 1 ? "student" : "students"}.`,
  },
  homePage: {
    eyebrow: "Free for ESL teachers",
    title: "English activities your class will actually enjoy",
    subtitle:
      "Quizzes, flashcards, team games and discussion cards, ready to project in class or share with students in one click.",
    browse: "Browse activities",
    signUp: "Sign up free",
    dashboard: "Go to your dashboard",
    stats: "At a glance",
    activities: (n: number) => (n === 1 ? "activity" : "activities"),
    categories: "categories",
    free: "Free",
    freeDetail: "no paywall, no ads",
    featured: "Featured activities",
    featuredSubtitle: "A few favorites to start with",
    seeAll: "See all activities",
    categoriesTitle: "Explore by category",
    ctaTitle: "Save your favorites and build class lists",
    ctaText:
      "A free teacher account keeps your favorites, lists and recently played activities in one place.",
  },
  contact: {
    title: "Contact us",
    intro: "Questions, ideas for new activities or a mistake you spotted? Send us a message.",
    emailUs: "Or email",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    characters: (n: number, max: number) =>
      `${n.toLocaleString("en-US")} / ${max.toLocaleString("en-US")}`,
    send: "Send message",
    sending: "Sending…",
    sent: "Thanks! We'll get back to you soon.",
    sendAnother: "Send another message",
    error: "Couldn't send your message. Check your connection and try again.",
    privacy: "We only use these details to answer you. See the",
    privacyLink: "Privacy Policy",
  },
  share: {
    title: "Share with students",
    subtitle: "Students open it on their own device. No account needed.",
    link: "Student link",
    copy: "Copy link",
    copied: "Copied!",
    copyHint: (mac: boolean) => `Press ${mac ? "⌘C" : "Ctrl+C"} to copy`,
    qr: (title: string) => `QR code for ${title}`,
    showFullscreen: "Show fullscreen",
    closeFullscreen: "Close fullscreen",
    native: "Share…",
    close: "Close",
    groupHint: "Best used in class: this activity is made for the whole group around one screen.",
    scan: "Scan to open",
  },
  admin: {
    title: "Content",
    subtitle: "Create, edit and review activities.",
    notAuthorized: "Not authorized",
    notAuthorizedHint: "This area is for content admins. Ask an admin to give you access.",
    newActivity: "New activity",
    rebuild: "Rebuild site",
    rebuildHint: "Static pages and the sitemap update on the daily build. Run it now on GitHub.",
    import: "Import JSON",
    exportAll: "Export all",
    formTab: "Form",
    errorSummary: (n: number) => `${n} ${n === 1 ? "thing" : "things"} to fix before publishing:`,
    livePreview: "Live preview",
    previewWidth: "Preview width",
    thumbnailTitle: "Thumbnail (card image, 16:10)",
    plan: {
      open: "Plan images",
      title: "Plan a picture for every item",
      text: "Adds a picture (file name, description and prompt) to each question, card, sentence or clue without one. Edit the descriptions, save, then generate and upload them from Missing images. Students see a stand-in until each picture is uploaded.",
      answers: "Also picture answers (an image for every option)",
      count: (n: number) => `${n} ${n === 1 ? "picture" : "pictures"} to plan`,
      none: "Every item already has a picture.",
      action: (n: number) => `Plan ${n} ${n === 1 ? "picture" : "pictures"}`,
      done: (n: number) =>
        `${n} ${n === 1 ? "picture" : "pictures"} planned. Review the descriptions and save.`,
    },
    typeChangeConfirm:
      "Start this type from an example? The current content doesn't fit the new type.",
    previewDesktop: "Desktop",
    previewPhone: "Phone",
    previewInvalid: "Fix the errors to see the preview.",
    upload: {
      prompt: "Image prompt",
      promptHint: "What to paste into the AI image tool. Saved with the activity.",
      writeFromAlt: "Write prompt from alt",
      copyPrompt: "Copy prompt",
      copied: "Copied!",
      upload: "Upload image",
      chooseFile: "Choose an image file",
      replace: "Replace image",
      needsSlug: "Set the slug first: images are saved under it.",
      notConnected: "Connect GitHub to upload images.",
      connect: "Connect GitHub",
      processing: (n: number) => `Preparing ${n === 1 ? "the image" : `${n} images`}…`,
      committing: "Uploading to GitHub…",
      done: "Uploaded. It goes live after the next deploy (~3 min).",
      seeDeploy: "See the deploy",
      failed: "The upload failed. Try again.",
      unreadable: "This file isn't an image the browser can read. Use PNG, JPG, WebP or AVIF.",
      several: "Upload several",
      severalHint:
        "Pick files named <slug>--<name>.png, as shown under each image. One commit for all.",
      unknownFiles: (names: string[]) => `Skipped (name not in the list): ${names.join(", ")}`,
      uploaded: "Uploaded",
      uploadedLiveAfterDeploy: "Uploaded — live after the deploy",
      attach: "Attach",
      queued: "Queued",
      queuedSummary: (n: number, kb: number) =>
        `${n} ${n === 1 ? "image queued" : "images queued"} · ${kb} KB`,
      sendAll: (n: number) => `Send all (${n})`,
      clearQueue: "Clear queue",
      clearQueueConfirm: "Clear all queued images?",
      queueFull: "Queue is full — send what you have first",
      storageUnavailableWarning:
        "Your queue won't survive a reload in this browser",
      alreadyOnSite: "Already on the site",
      uploadProgress: (current: number, total: number) =>
        `Uploading ${current} of ${total}…`,
      unsavedWarning: (n: number) =>
        `You have ${n} ${n === 1 ? "image" : "images"} not sent yet. Leave anyway?`,
      filterAll: "All",
      filterMissing: "Missing",
      filterQueued: "Queued",
      filterThumbnailsOnly: "Thumbnails only",
      tryAgain: "Try again",
      remove: "Remove",
    },
    settings: {
      title: "Settings",
      githubTitle: "GitHub (image uploads)",
      githubText:
        "Images you upload are committed to the repository and go live with the next deploy. Connect a GitHub token that can only write this repository's files. It's kept in this browser only.",
      steps: [
        "Open GitHub → Settings → Developer settings → Fine-grained tokens → Generate new token.",
        'Name it "Fun English admin", pick an expiration (e.g. 90 days).',
        "Repository access: Only select repositories → nfbrentano/FunEnglish.",
        "Permissions → Repository permissions → Contents: Read and write. Nothing else.",
        "Generate the token, copy it and paste it below.",
      ],
      openGitHub: "Create a token on GitHub",
      token: "GitHub token",
      connectAction: "Connect",
      checking: "Checking…",
      connected: (login: string) => `Connected as ${login}`,
      connectedHere: "This browser can upload images.",
      disconnect: "Disconnect",
    },
    history: {
      open: "History",
      title: "Version history",
      loading: "Loading versions…",
      empty: "No saved versions yet.",
      versions: "Saved versions",
      latest: "latest",
      pick: "Pick a version to see what's different from the editor now.",
      same: "Same as the editor now.",
      differences: (n: number) =>
        `${n} ${n === 1 ? "difference" : "differences"} (crossed out: now · green: this version)`,
      more: (n: number) => `…and ${n} more`,
      restore: "Restore this version",
      restoreConfirm: "Restore this version? It's saved as a new version, so you can undo it.",
      restored: "Version restored",
    },
    tooLarge: (kb: number) => `This activity is too large (${kb} KB; max 200 KB).`,
    create: {
      basics: "Type, category and level",
      level: "Level",
      blankTitle: "Start blank",
      blankText: "An empty activity of this type, ready to fill in the form.",
      blankAction: "Start blank",
      exampleTitle: "Start from an example",
      exampleText: "A small, valid example of this type to adapt.",
      exampleAction: "Use the example",
      aiTitle: "Create with AI (copy prompt)",
      aiText:
        "Copy a ready-made prompt into any AI chat (ChatGPT, Gemini, Claude…), then paste its answer here. It becomes a draft pending review.",
      topic: "Topic",
      topicPlaceholder: "e.g. weather, ordering food, past simple",
      count: "How many items",
      step1: "Copy this prompt and paste it into an AI chat.",
      prompt: "Prompt for the AI",
      copyPrompt: "Copy prompt",
      step2: "Paste the AI's answer (the JSON) here:",
      createDraft: "Create draft",
      jsonTitle: "Paste JSON",
      jsonText: "An activity in the content/activities format (e.g. from Export JSON).",
      invalid: "This doesn't make a valid activity yet:",
    },
    form: {
      moveUp: (name: string) => `Move ${name} up`,
      moveDown: (name: string) => `Move ${name} down`,
      duplicate: (name: string) => `Duplicate ${name}`,
      remove: (name: string) => `Remove ${name}`,
      // Quiz
      questions: "Questions",
      question: (n: number) => `Question ${n}`,
      addQuestion: "Add question",
      prompt: "Question",
      options: "Options",
      optionOf: (o: number, q: number) => `Option ${o} of question ${q}`,
      addOption: "Add option",
      correct: "Correct",
      markCorrect: (o: number, q: number) => `Option ${o} is correct (question ${q})`,
      chooseAll: "Choose all that apply (several correct options)",
      explanation: "Explanation",
      explanationHint: "One sentence that teaches the rule, shown after answering.",
      // Media
      media: "Media",
      mediaKinds: {
        none: "None",
        image: "Image",
        emoji: "Emoji",
        tts: "Read aloud",
        youtube: "YouTube clip",
      },
      mediaPreview: "Preview",
      imageSrc: "Image",
      imageSrcHint: "Pick an image of the site or paste an https:// URL.",
      imageSource: "Source",
      sourceAi: "AI-generated",
      sourceStock: "Stock",
      sourceOwn: "Own",
      imageAlt: "Image description (alt)",
      emoji: "Emoji",
      emojiLabel: "What the emoji show",
      emojiLabelHint: "Read by screen readers.",
      ttsText: "Text read aloud",
      listen: "Listen",
      youtubeLink: "YouTube link",
      youtubeInvalid: "That isn't a YouTube video link.",
      videoId: "Video id",
      start: "Start (seconds)",
      end: "End (seconds)",
      // Fill in the blanks
      mode: "Mode",
      modeTyping: "Typing",
      modeWordBank: "Word bank",
      sentences: "Sentences",
      sentence: (n: number) => `Sentence ${n}`,
      addSentence: "Add sentence",
      sentenceText: "Sentence",
      sentenceHint: "Select a word and press Make blank, or type [[answer]].",
      makeBlank: "Make blank",
      blanks: "Blanks",
      blank: (n: number) => `Blank ${n}`,
      alternatives: "Other accepted answers, comma separated",
      alternativesFor: (answer: string, n: number) =>
        `Other accepted answers for blank ${n} (${answer})`,
      removeBlank: (n: number) => `Turn blank ${n} back into text`,
      hint: "Hint",
      distractors: "Extra words for the word bank",
      distractorsHint: "Comma separated. Only used in Word bank mode.",
      credit: "Song or video credit",
      creditFields: { title: "Title", artist: "Artist", url: "Link" },
      // Sentence Builder
      orderSentenceHint: "The correct sentence. Its final punctuation stays fixed at the end.",
      splitByWords: "Split by words",
      useDefaultSplit: "One piece per word",
      pieces: "Pieces students will order",
      piecesDefault: "One piece per word. Split by words to join some into chunks.",
      joinPieces: (left: string, right: string) => `Join “${left}” and “${right}”`,
      splitPiece: (piece: string) => `Split “${piece}” into words`,
      orderAlternatives: "Other accepted orders, one per line",
      orderAlternativesHint: "Same words, another order (e.g. Yesterday I went home).",
      translation: "Translation",
      // Flashcards
      cards: "Cards",
      card: (n: number) => `Card ${n}`,
      addCard: "Add card",
      front: "Front",
      frontText: "Text or emoji",
      frontHint: "The front needs text, an image or both.",
      withImage: "With an image",
      back: "Back",
      word: "Word",
      definition: "Definition",
      example: "Example sentence",
      speak: "Read aloud",
      speakHint: "What the speaker button says (optional).",
      // Quiz board
      boardSize: (c: number, r: number) => `${c} categories × ${r} values`,
      addRow: (value: number) => `Add row (${value})`,
      removeRow: (value: number) => `Remove row (${value})`,
      categories: "Categories",
      category: (n: number) => `Category ${n}`,
      addCategory: "Add category",
      categoryName: "Category name",
      value: "Points",
      clueQuestion: (category: string, value: number) => `${category} for ${value}`,
      answer: "Answer",
      // Discussion cards
      writingMode: "Writing mode (a text box with a word counter)",
      cardPrompt: "Prompt",
      thisOrThat: "This or That (two choices)",
      choice: (n: number) => `Choice ${n}`,
      followUps: "Follow-up questions",
      followUp: (f: number, c: number) => `Follow-up ${f} of card ${c}`,
      addFollowUp: "Add follow-up",
      vocabulary: "Useful vocabulary",
      commaHint: "Comma separated.",
    },
    unsavedLeave: "You have unsaved changes. Leave without saving?",
    localDraft: (time: string) => `You have unsaved changes from ${time} on this device.`,
    restoreDraft: "Restore",
    discardDraft: "Discard",
    unsaved: "Unsaved changes",
    conflictTitle: "Someone saved this activity after you opened it",
    conflictText:
      "Reload to see their version (your changes here will be lost), or overwrite it with yours.",
    conflictReload: "Reload their version",
    conflictOverwrite: "Overwrite",
    importError: "That file isn't a valid activity.",
    needsReview: "Needs review",
    needsReviewCount: (n: number) => `${n} need${n === 1 ? "s" : ""} review`,
    aiBadge: "AI · Needs review",
    search: "Search by title",
    allStatuses: "All statuses",
    allTypes: "All types",
    coverage: {
      title: "Coverage",
      subtitle:
        "Where the collection is thin. Cells with fewer than 3 published activities are highlighted.",
      byLevel: "By level",
      byType: "By type",
      category: "Category",
      cell: (published: number, drafts: number) =>
        drafts > 0 ? `${published} published, ${drafts} drafts` : `${published} published`,
      create: (category: string, column: string) => `Create a ${column} activity for ${category}`,
      open: (category: string, column: string) => `Open ${category} · ${column}`,
      pictures: "Pictures per activity",
      picturesText:
        "Items with an uploaded picture (planned ones count once uploaded). Targets: 80% for Beginner and Intermediate, 50% for Advanced.",
      activity: "Activity",
      level: "Level",
      itemsCol: "Items",
      plannedCol: "Planned",
      uploadedCol: "Uploaded",
      belowTarget: (target: number) => `below the ${target}% target`,
    },
    images: {
      title: "Missing images",
      subtitle:
        "Images used by activities that aren't in the site yet. Generate each one, save it with the file name shown, then run npm run images:import -- <folder>.",
      none: "Every image is in place.",
      fileName: "Save as",
      copyPrompt: "Copy prompt",
      copied: "Copied!",
      count: (n: number) => `${n} ${n === 1 ? "image" : "images"} to generate`,
      siteImage: "site image (shown when an activity has none)",
    },
    list: {
      sortBy: "Sort by",
      sorts: {
        updated: "Recently updated",
        title: "Title (A–Z)",
        category: "Category",
        status: "Drafts first",
      },
      level: "Level",
      featured: "Featured",
      missingImage: "Missing image",
      fewImages: "Few images",
      selectAll: (n: number) => `Select all ${n} activities shown by the filters`,
      selectOne: (title: string) => `Select ${title}`,
      selected: (n: number) => `${n} selected`,
      bulkActions: "Bulk actions",
      clear: "Clear selection",
      publish: "Publish",
      unpublish: "Unpublish",
      markReviewed: "Mark as reviewed",
      moveTo: "Move to category",
      feature: "Feature",
      unfeature: "Unfeature",
      delete: "Delete",
      deleteTitle: (n: number) => `Delete ${n} ${n === 1 ? "activity" : "activities"}?`,
      deleteHint: (n: number) => `This can't be undone. Type ${n} to confirm.`,
      deleteConfirm: "Delete forever",
      done: (n: number) => `Done: ${n} ${n === 1 ? "activity" : "activities"} updated`,
      deleted: (n: number) => `${n} ${n === 1 ? "activity" : "activities"} deleted`,
      skipped: (titles: string[]) =>
        `${titles.length} not published (fix their errors first): ${titles.join(", ")}`,
      page: (from: number, to: number, total: number) => `${from}–${to} of ${total}`,
      previous: "Previous page",
      next: "Next page",
      catalogSize: (percent: number) =>
        `The catalog index is ${percent}% full. Above ~1,500 activities it will need to be split (spec RNF03).`,
      coverage: "Coverage",
      missingImages: "Missing images",
    },
    columns: {
      title: "Title",
      category: "Category",
      type: "Type",
      status: "Status",
      updated: "Updated",
    },
    statuses: { draft: "Draft", published: "Published" },
    empty: "No activities match these filters.",
    loading: "Loading activities",
    back: "All activities",
    editTitle: "Edit activity",
    newTitle: "New activity",
    fields: {
      title: "Title",
      slug: "Slug (URL)",
      description: "Description",
      category: "Category",
      levelMin: "Lowest level",
      levelMax: "Highest level",
      type: "Type",
      tags: "Tags (comma separated)",
      thumbnail: "Thumbnail path or URL",
      thumbnailAlt: "Thumbnail description (alt)",
      featured: "Featured on the home page",
    },
    slugTaken: "Slug already in use",
    content: "Content",
    texts: "Texts",
    json: "JSON",
    textsHint:
      "Every text of the activity. Structure changes (adding questions, answers…) go in the JSON tab.",
    insertTemplate: "Insert template",
    templateConfirm: "Replace the current content with an example?",
    invalidJson: "This isn't valid JSON yet.",
    errorsTitle: "Fix these before publishing:",
    valid: "Ready to publish",
    preview: "Preview",
    closePreview: "Close preview",
    saveDraft: "Save draft",
    publish: "Publish",
    unpublish: "Unpublish",
    saveChanges: "Save changes",
    duplicate: "Duplicate",
    exportJson: "Export JSON",
    delete: "Delete",
    deleteTitle: "Delete this activity?",
    deleteHint: (title: string) => `This can't be undone. Type "${title}" to confirm.`,
    deleteConfirm: "Delete forever",
    markReviewed: "Mark as reviewed",
    saveAndNext: "Save & next",
    reviewedBy: (date: string) => `Reviewed on ${date}`,
    pendingReview: "AI-generated, not reviewed yet",
    saved: "Saved",
    published: "Published: it's in the catalog now",
    deleted: "Activity deleted",
    saveError: "Couldn't save. Check your connection and try again.",
    edit: "Edit activity",
    copy: "copy",
  },
  quiz: {
    correct: "Correct!",
    notQuite: "Not quite",
    timeUp: "Time's up!",
    next: "Next",
    seeResults: "See results",
    check: "Check",
    chooseAll: "Choose all correct answers",
    turn: (team: string) => `${team}'s turn`,
    secondsLeft: (n: number) => `${n}s`,
  },
  catalog: {
    title: "Fun English Activities",
    count: (n: number) =>
      `${n.toLocaleString("en-US")} Interactive ${n === 1 ? "Activity" : "Activities"} for ESL Teachers`,
    searchLabel: "Search activities",
    searchPlaceholder: "Search by topic, level, grammar point, or activity name…",
    whatsNew: "What's New",
    whatsNewSubtitle: "Recently added activities",
    seeAll: "See All",
    carouselLabel: (section: string) => `${section} activities`,
    seeAllIn: (section: string) => `See all ${section} activities`,
    previous: (section: string) => `Previous ${section} activities`,
    next: (section: string) => `Next ${section} activities`,
    newBadge: "New",
    loginToFavorite: "Log in to save favorites",
    share: "Share",
    empty: "No activities yet. Check back soon!",
    showing: (n: number) =>
      `Showing ${n.toLocaleString("en-US")} ${n === 1 ? "activity" : "activities"}`,
    categoryFilter: "Category",
    allCategories: "All Categories",
    levelFilter: "Level",
    allLevels: "All Levels",
    sortLabel: "Sort by",
    sorts: { newest: "Newest First", "title-asc": "Title: A-Z", "title-desc": "Title: Z-A" },
    levels: { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" },
    clearFilters: "Clear filters",
    results: "Search results",
    noResults: "No activities found",
    noResultsHint: "Try other words or clear the filters.",
    loadMore: "Load more",
    activityCount: (n: number) =>
      `${n.toLocaleString("en-US")} ${n === 1 ? "activity" : "activities"}`,
    emptyCategory: "No activities in this category yet",
    browseAll: "Browse all activities",
    allNew: "All activities, newest first",
    loading: "Loading activities",
  },
  vocabulary: {
    title: "Vocabulary Bank",
    subtitle: "Words and phrases recorded for this student.",
    addWord: "Add word",
    editWord: "Edit word",
    termLabel: "Term or expression",
    termPlaceholder: "e.g. boarding pass",
    meaningLabel: "Meaning / Translation (optional)",
    meaningPlaceholder: "e.g. cartão de embarque",
    exampleLabel: "Example sentence (optional)",
    examplePlaceholder: "e.g. Please show your boarding pass at the gate.",
    saveWord: "Save word",
    deleteWord: "Delete word",
    confirmDeleteWord: (term: string) => `Delete "${term}" from vocabulary?`,
    wordAdded: "Word added to vocabulary bank",
    wordUpdated: "Word updated",
    wordDeleted: "Word deleted",
    duplicateNotice: "Word updated with this lesson's session.",
    seenInClasses: (n: number) => `seen in ${n} ${n === 1 ? "class" : "classes"}`,
    studentsCount: (n: number) => `${n} ${n === 1 ? "student" : "students"}`,
    filterSearch: "Search words...",
    emptyList: "No words in vocabulary bank yet.",
    noWordsFound: "No words found matching your search.",
    learned: "Learned",
    learning: "Learning",
    reviewStats: {
      mastered: (n: number) => `${n} mastered`,
      inReview: (n: number) => `${n} in review`,
      due: (n: number) => `${n} due`,
      lastReview: (date: string) => `Last review: ${date}`,
      noReviewsYet: "No reviews yet",
    },
  },
  portal: {
    title: "Student Portal",
    welcome: (name: string) => `Welcome back, ${name}!`,
    teacherSelector: "Teacher",
    tabs: {
      overview: "My Learning",
      tracks: "Learning path",
      words: "My words",
      history: "Class history",
    },
    wordsTitle: "My Words",
    wordsSubtitle: "Vocabulary and expressions introduced in your classes.",
    searchWordsPlaceholder: "Search words...",
    sortRecent: "Most recent",
    sortAlphabetical: "A–Z",
    filterAll: "All words",
    filterToLearn: "To learn",
    filterLearned: "Learned",
    noWordsFound: "No words found matching your search.",
    markLearned: "I know this",
    markToLearn: "Still learning",
    learnedBadge: "Learned ✓",
    practiceButton: "Practice",
    dailyReviewButton: (n: number) => `Daily Review (${n})`,
    practiceTooltipEmpty: "Add words in class to practice",
    practiceModalTitle: "Practice Flashcards",
    practiceCardOf: (current: number, total: number) => `Card ${current} of ${total}`,
    listenPronunciation: "Listen to pronunciation",
    strengthsTitle: "Strengths",
    strengthsEmpty: "No strengths shared yet. Keep practicing in class!",
    toReviewTitle: "To review",
    toReviewEmpty: "Nothing to review right now. Great job!",
    seenInClasses: (n: number) => `seen in ${n} ${n === 1 ? "class" : "classes"}`,
    masteredTitle: "Mastered ✓",
    masteredEmpty: "Mastered items will appear here as you resolve errors.",
    homeworkTitle: "Homework",
    homeworkEmpty: "No homework assigned right now.",
    progressTitle: "My progress",
    progressEmpty: "No progress track assigned yet.",
    classHistoryTitle: "Class history",
    classHistoryEmpty: "No class summaries available yet.",
    activitiesPracticed: "Activities practiced",
    wordsLearned: "Vocabulary & Key Words",
    whiteboardNotes: "Whiteboard notes",
    classNotes: "Class notes",
    individualNotes: "Notes for you",
    duration: (mins: number) => `${mins} min`,
    notConnectedTitle: "You're not connected to a teacher yet",
    notConnectedDesc:
      "Ask your English teacher for an invite link or QR code to connect your account.",
    practiceCatalog: "Practice activities",
    joinTitle: "Join Student Portal",
    joinSubtitle: "Connect your account to review feedback, notes and homework from your teacher.",
    joinTeacherWelcome: (student: string, teacher: string) =>
      `Hi ${student}! Connect to ${teacher}'s class on Fun English.`,
    invalidInvite:
      "This invite is invalid or has expired. Ask your teacher for a new one.",
    redeemButton: "Connect to student portal",
    redeeming: "Connecting…",
    accountNotice:
      "Sign in or create a free student account below to link this invite.",
    copySummaryButton: "Copy summary",
    summaryCopied: "Class summary copied for WhatsApp!",
    inviteSectionTitle: "Student Portal Access",
    inviteToPortal: "Invite to student portal",
    generatingInvite: "Generating invite…",
    expiresInDays: "Expires in 14 days",
    copyInviteLink: "Copy link",
    inviteLinkCopied: "Invite link copied to clipboard!",
    inviteCodeLabel: "Invite code:",
    revokeInvite: "Revoke invite",
    confirmRevokeInvite:
      "Revoke this portal invite? The code and link will stop working immediately.",
    removePortalAccess: "Remove portal access",
    confirmRemovePortalAccess:
      "Remove portal access for this student? They will lose access to the portal immediately.",
    portalConnected: "Connected to portal",
    portalConnectedDesc:
      "This student can sign in to view shared notes, strengths, and class history.",
    scanQrHint: "Scan with a mobile phone camera to join:",
  },
  classroomTimer: {
    title: "Timer",
    countdown: "Countdown",
    stopwatch: "Stopwatch",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    plus30s: "+30 s",
    minus30s: "−30 s",
    timesUp: "Time's up!",
    bigScreen: "Big screen",
    closeBigScreen: "Close big screen",
    mute: "Mute sound",
    unmute: "Unmute sound",
    customTimeLabel: "Custom time",
    customTimePlaceholder: "mm:ss",
    customTimeError: "Enter a time up to 99:59",
    presets: {
      s30: "30 s",
      m1: "1 min",
      m2: "2 min",
      m3: "3 min",
      m5: "5 min",
      m10: "10 min",
    },
    ariaTimerRunning: "Timer running",
    ariaTimerPaused: "Timer paused",
    ariaTimerCompleted: "Timer completed",
  },
  classroomPicker: {
    title: "Picker & Groups",
    wheelTab: "Wheel",
    groupsTab: "Groups",
    namesTab: "Names",
    rosterTab: "Class roster",
    customTab: "Custom list",
    spin: "Spin",
    spinning: "Spinning…",
    spinAgain: "Spin again",
    skip: "Skip",
    bigScreen: "Big screen",
    closeBigScreen: "Close big screen",
    resetCycle: "Reset cycle",
    noRepeatLabel: "Don't repeat until everyone is picked",
    everyonePickedNotice: "Everyone has been picked — starting over",
    addAtLeast2Names: "Add at least 2 names",
    notEnoughStudentsForGroups: (n: number) => `Not enough students for ${n} groups`,
    shuffleAgain: "Shuffle again",
    copyGroups: "Copy groups",
    copied: "Groups copied!",
    recentPicks: "Recent picks",
    noRecentPicks: "No picks yet",
    clearHistory: "Clear history",
    winnerHeading: "Selected Student",
    winnerSubtitle: "It's your turn to answer!",
    groupCountLabel: "Number of groups",
    groupSizeLabel: "Students per group",
    splitByGroups: "Split by number of groups",
    splitBySize: "Split by students per group",
    generateGroups: "Generate groups",
    customNamesPlaceholder: "Paste or type names, one per line…",
    customNamesHint: "Names are automatically saved in your browser.",
    studentsCount: (count: number) => `${count} student${count === 1 ? "" : "s"}`,
    remainingCount: (remaining: number, total: number) => `${remaining} of ${total} remaining`,
  },
  whiteboard: {
    title: "Whiteboard",
    pen: "Pen",
    highlighter: "Highlighter",
    eraser: "Eraser",
    text: "Text",
    select: "Select & Move",
    undo: "Undo",
    redo: "Redo",
    clear: "Clear board",
    clearConfirm: "Clear this board? All strokes, text, and images on this page will be removed.",
    clearConfirmButton: "Clear page",
    cancel: "Cancel",
    expandBoard: "Expand board",
    collapseBoard: "Collapse board",
    exportPng: "Export PNG",
    sendWords: "Send words to students",
    sendWordsDesc: "Choose which words from the board to add to the student vocabulary list for this session:",
    sendWordsConfirm: "Add to vocabulary",
    sendWordsSuccess: (count: number) => `Added ${count} word${count === 1 ? "" : "s"} to vocabulary!`,
    noWordsFound: "No words found in text boxes on this board.",
    pageOf: (current: number, total: number) => `Page ${current} of ${total}`,
    prevPage: "Previous page",
    nextPage: "Next page",
    addPage: "Add new page",
    deletePage: "Delete page",
    deletePageConfirm: "Delete this page and its contents?",
    onlyImagesAllowed: "Only images can be pasted",
    backgroundWhite: "Plain",
    backgroundGrid: "Grid",
    backgroundLines: "Lined",
    thin: "Thin",
    medium: "Medium",
    thick: "Thick",
    black: "Black",
    red: "Red",
    blue: "Blue",
    green: "Green",
    yellow: "Yellow",
    purple: "Purple",
    typeTextHere: "Type text here…",
    pastingImage: "Processing image…",
    imageTooLarge: "Image must be under 2 MB",
    offlineNotice: "Saved offline in browser",
  },
  session: {
    startClass: "Start class",
    endClass: "End class",
    resumeClass: (className: string) => `Resume class "${className}"?`,
    resumePromptTitle: "Resume active session?",
    resumePromptDesc: (className: string) =>
      `You have an ongoing session for "${className}". Would you like to resume where you left off?`,
    resume: "Resume class",
    discard: "Discard",
    activeSession: "Active session",
    pastClasses: "Past classes",
    pastClassesEmpty: "No past classes recorded yet for this class.",
    conflictTitle: "Active class session already in progress",
    conflictDesc: (currentClassName: string, newClassName: string) =>
      `Class "${currentClassName}" is currently active. You can only run one session at a time. What would you like to do before starting "${newClassName}"?`,
    resumeExisting: "Resume existing class",
    endExisting: "End & review current class",
    discardExisting: "Discard current class",
    projectionMode: "Projection mode",
    projectionModeDesc: "Hides private notes, emails, and sensitive data from the projector.",
    projectionModeOn: "Projection mode ON",
    projectionModeOff: "Projection mode OFF",
    tabs: {
      timer: "Timer",
      board: "Board",
      picker: "Picker",
      notes: "Notes",
      students: "Students",
    },
    students: {
      title: "Attendance",
      present: "Present",
      absent: "Absent",
      presentCount: (present: number, total: number) => `${present} of ${total} present`,
      allPresent: "Mark all present",
    },
    notes: {
      title: "Session notes",
      quickNotePlaceholder: "Type note and press Enter…",
      selectStudent: "Select student…",
      noNotesYet: "No notes taken during this session yet.",
      privateBadge: "Private",
      sharedBadge: "Shared",
      wholeClass: "Whole class",
    },
    review: {
      title: "Class Summary Review",
      subtitle: "Review attendance, activities, vocabulary and notes before saving and publishing.",
      duration: "Duration",
      durationMinutes: (min: number) => `${min} min`,
      attendanceHeading: "Attendees",
      activitiesHeading: "Activities Played",
      noActivities: "No activities played during this session.",
      wordsHeading: "Vocabulary & Key Words",
      noWords: "No vocabulary recorded.",
      addWordPlaceholder: "Add a word or phrase…",
      boardHeading: "Whiteboard Content",
      notesHeading: "Student Feedback & Notes",
      noNotes: "No notes recorded.",
      classNotesHeading: "Whole Class Notes",
      classNotesPlaceholder: "Notes, assignments, or announcements for the whole class…",
      confirmEnd: "Confirm & End Class",
      saving: "Saving class summary…",
      savedSuccess: "Class session ended and summary published!",
      copyWhatsApp: "Copy summary for WhatsApp",
      copiedWhatsApp: "Summary copied to clipboard!",
    },
  },
  homework: {
    sendHomework: "Send as homework",
    sendModalTitle: "Send as homework",
    destinationStep: "Destination",
    targetClass: "Class",
    targetStudents: "Selected students",
    targetAnyone: "Anyone with the link",
    selectClass: "Select class…",
    selectStudents: "Select students…",
    dueDateLabel: "Due date (optional)",
    allowLateLabel: "Allow late submissions",
    instructionLabel: "Instructions (optional, up to 300 characters)",
    instructionPlaceholder: "E.g. Practice before our next class on Friday…",
    generating: "Generating links…",
    generateButton: "Generate Homework Link",
    createdSuccess: "Homework link ready!",
    classLinkTitle: "Class Link",
    classLinkDesc: "Students pick their name and enter their 4-digit PIN.",
    individualLinksTitle: "Individual Student Links",
    individualLinksDesc: "Direct personal links with automatic identification (no PIN or name selection required).",
    copyLink: "Copy",
    copyAll: "Copy all",
    copied: "Copied!",
    allCopied: "All student links copied!",
    whatsappShare: "Share via WhatsApp",
    qrCode: "QR Code",
    qrCodeTitle: "Homework QR Code",
    regenerateLink: "Regenerate link",
    confirmRegenerateToken: "Regenerate individual link for this student? The old link will stop working immediately.",
    greeting: (name: string) => `Hi, ${name}!`,
    selectYourName: "Select your name",
    enterPin: "Enter your 4-digit PIN",
    pinPlaceholder: "PIN",
    startHomework: "Start Homework",
    enterYourName: "Enter your name",
    namePlaceholder: "Your name",
    invalidLinkTitle: "This homework link is not valid",
    invalidLinkDesc: "Please check the link or ask your teacher for a new one.",
    closedTitle: "This homework is closed",
    closedDesc: "The deadline for this homework has passed and late submissions are not allowed.",
    usedAttemptsTitle: "You've used all 3 attempts",
    usedAttemptsDesc: "Your attempts have already been submitted to your teacher.",
    wrongPin: "Wrong PIN",
    tooManyAttempts: "Too many attempts — ask your teacher",
    sentToTeacher: "Sent to your teacher ✓",
    timeSpent: (sec: number) => `${Math.floor(sec / 60)}m ${sec % 60}s`,
    dashboardTitle: "Homework",
    emptyDashboard: "No homework tasks assigned yet. Click \"Send as homework\" on any activity to assign it to your students.",
    browseActivities: "Explore activities to assign",
    filterAll: "All",
    filterOpen: "Open",
    filterClosed: "Closed",
    filterOverdue: "Overdue",
    doneRatio: (done: number, total: number) => `${done}/${total} done`,
    submissionsHeading: "Submissions",
    noSubmissions: "No submissions yet.",
    studentColumn: "Student",
    scoreColumn: "Score",
    timeColumn: "Time",
    dateColumn: "Submitted",
    viaColumn: "Identification",
    attemptsColumn: "Attempts",
    pendingHeading: "Pending Students",
    closeTask: "Close homework",
    reopenTask: "Re-open homework",
    deleteTask: "Delete task",
    confirmDelete: "Delete this homework task and its submissions?",
    pinLockoutAlert: (studentName: string) => `⚠️ ${studentName}'s PIN is temporarily locked due to 5 failed attempts.`,
    completedBadge: "Completed",
    lateBadge: "Late",
    tabs: {
      submissions: "Submissions",
      questions: "Questions",
    },
    questionAnalysis: {
      title: "Question Analysis",
      accuracy: (pct: number) => `${pct}% correct`,
      mostMissedTitle: "Most Missed Questions",
      correctAnswer: "Correct Answer",
      givenAnswer: "Student Answer",
      missedBy: (names: string) => `Missed by: ${names}`,
      missedCount: (n: number) => `${n} ${n === 1 ? "student" : "students"} missed this`,
      suggestedNotes: "Suggested Error Notes",
      addAsNote: "Add as note",
      addAllNotes: "Add all as notes",
      noteAdded: "Error note added",
      notesAddedBatch: (added: number, skipped: number) =>
        `${added} note${added === 1 ? "" : "s"} added${skipped > 0 ? ` (${skipped} duplicate${skipped === 1 ? "" : "s"} skipped)` : ""}`,
      questionChanged: "Question changed",
      noErrors: "Great job! No errors recorded in this submission.",
    },
  },
} as const;

